/**
 * What the host must send with each file — defined once, written out for every
 * host we support, and applied to `vite preview` so the production test run
 * exercises exactly what users will receive (D-094).
 *
 * Kept as data rather than as two hand-written files because the security
 * policy is the part most likely to break the app silently. A policy that is
 * wrong only on one host is a bug nobody sees until a user on that host does.
 */

/**
 * The Content Security Policy, reasoned from what the bundle actually does.
 *
 *   'wasm-unsafe-eval'  the HEIC decoder and the AAC encoder are WebAssembly.
 *                       Nothing in the bundle uses eval or new Function, so
 *                       the far broader 'unsafe-eval' is not needed.
 *   worker-src blob:    Mediabunny starts its helper workers from in-memory
 *                       scripts; the export worker itself is a same-origin file.
 *   style 'unsafe-inline'  React's style attributes are inline styles. Scripts
 *                       stay strict, which is where the protection matters.
 *   blob: and data:     the user's own photos, clips and exports live in memory
 *                       as blob URLs; nothing is fetched from anywhere else.
 *
 * No third-party origin appears anywhere. Fonts, samples and templates all ship
 * with the app, which is the policy's way of stating §9's promise.
 */
export const CONTENT_SECURITY_POLICY = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'",
  "worker-src 'self' blob:",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' blob: data:",
  "media-src 'self' blob:",
  "font-src 'self' data:",
  "connect-src 'self' blob: data:",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join('; ');

/** Sent with every response. */
export const SECURITY_HEADERS: Readonly<Record<string, string>> = {
  'Content-Security-Policy': CONTENT_SECURITY_POLICY,
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()',
  'X-Frame-Options': 'DENY',
};

/**
 * Caching, by path.
 *
 * Everything under /assets has a content hash in its name, so it never changes
 * and can be kept for a year. The page, the service worker and the manifest
 * must always be checked, or people keep yesterday's version for days after an
 * update. Thumbnails, samples and fonts have fixed names but rarely change, and
 * the service worker re-fetches them by revision anyway.
 */
export const CACHE_RULES: readonly { readonly pattern: string; readonly value: string }[] = [
  { pattern: '/assets/*', value: 'public, max-age=31536000, immutable' },
  { pattern: '/thumbs/*', value: 'public, max-age=86400' },
  { pattern: '/samples/*', value: 'public, max-age=86400' },
  { pattern: '/fonts/*', value: 'public, max-age=2592000' },
  { pattern: '/index.html', value: 'no-cache' },
  { pattern: '/sw.js', value: 'no-cache' },
  { pattern: '/registerSW.js', value: 'no-cache' },
  { pattern: '/manifest.webmanifest', value: 'no-cache' },
];

/** Cloudflare Pages (and Netlify) read `_headers` from the output folder. */
export function cloudflareHeaders(): string {
  const lines: string[] = [
    '# Generated by deploy/headers.ts at build time. Edit that file, not this one.',
    '/*',
    ...Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`),
    '',
  ];
  for (const rule of CACHE_RULES) lines.push(rule.pattern, `  Cache-Control: ${rule.value}`, '');
  // The site root serves index.html, so it needs the same rule.
  lines.push('/', '  Cache-Control: no-cache', '');
  return lines.join('\n');
}

/** Apache, which is what cPanel hosting runs. */
export function apacheHtaccess(): string {
  const exact = CACHE_RULES.filter((rule) => !rule.pattern.endsWith('/*'));
  const folders = CACHE_RULES.filter((rule) => rule.pattern.endsWith('/*'));
  const escape = (value: string): string => value.replace(/"/g, '\\"');

  return [
    '# Generated by deploy/headers.ts at build time. Edit that file, not this one.',
    '# For cPanel and other Apache hosts. Upload it with the rest of dist/.',
    '',
    '# Secure pages only: the video encoder and offline mode need HTTPS.',
    'RewriteEngine On',
    'RewriteCond %{HTTPS} !=on',
    'RewriteCond %{HTTP:X-Forwarded-Proto} !=https',
    'RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]',
    '',
    '# File types some shared hosts do not know yet.',
    'AddType application/manifest+json .webmanifest',
    'AddType video/webm .webm',
    'AddType image/webp .webp',
    'AddType font/woff2 .woff2',
    'AddType text/javascript .js .mjs',
    '',
    '<IfModule mod_headers.c>',
    ...Object.entries(SECURITY_HEADERS).map(([name, value]) => `  Header always set ${name} "${escape(value)}"`),
    '',
    ...exact.map((rule) => {
      const file = rule.pattern.slice(1).replace(/\./g, '\\.');
      return `  <FilesMatch "^${file}$">\n    Header set Cache-Control "${rule.value}"\n  </FilesMatch>`;
    }),
    ...folders.map((rule) => {
      const folder = rule.pattern.slice(0, -2);
      return `  <If "%{REQUEST_URI} =~ m#^${folder}/#">\n    Header set Cache-Control "${rule.value}"\n  </If>`;
    }),
    '</IfModule>',
    '',
    '# Text compresses well; the media and fonts are already compressed.',
    '<IfModule mod_deflate.c>',
    '  AddOutputFilterByType DEFLATE text/html text/css text/javascript application/javascript application/manifest+json image/svg+xml',
    '</IfModule>',
    '',
  ].join('\n');
}

/** Every header for one request path, for `vite preview`. */
export function headersFor(path: string): Record<string, string> {
  const headers: Record<string, string> = { ...SECURITY_HEADERS };
  const clean = path.split('?')[0] ?? path;
  const target = clean === '/' ? '/index.html' : clean;
  for (const rule of CACHE_RULES) {
    const hit = rule.pattern.endsWith('/*')
      ? target.startsWith(rule.pattern.slice(0, -1))
      : target === rule.pattern;
    if (hit) headers['Cache-Control'] = rule.value;
  }
  return headers;
}
