import { expect, test } from '@playwright/test';

/**
 * §13: installable and offline-capable.
 *
 * Only meaningful against the production build — the service worker that
 * makes the app work offline is generated by the build and deliberately off in
 * the dev server — so this runs under `npm run e2e:prod` and skips otherwise.
 *
 * It is the one promise in the spec that no other test exercised, and the one
 * a user is least likely to check until the moment they need it: opening the
 * app on a train.
 */

test.skip(process.env['PW_PROD'] !== '1', 'The service worker exists only in the production build.');

test('opens and works with no network once it has been visited', async ({ page, context }) => {
  /*
   * Generous, because the service worker has to download and cache the whole
   * app (about 7 MB) before it takes over — and in the full production run
   * every other test's browser is doing the same against one preview server
   * while video exports saturate the CPU. Alone it takes a second or two.
   */
  test.setTimeout(120_000);
  await page.goto('/');
  await page.waitForSelector('canvas');

  // Wait until the service worker controls the page and has finished
  // precaching — before that, going offline proves nothing.
  await page.evaluate(async () => {
    const registration = await navigator.serviceWorker.ready;
    if (!navigator.serviceWorker.controller) {
      await new Promise<void>((resolve) => {
        navigator.serviceWorker.addEventListener('controllerchange', () => { resolve(); }, { once: true });
      });
    }
    return registration.active?.state;
  });

  await context.setOffline(true);
  await page.reload();

  await expect(page.locator('canvas')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Export' })).toBeVisible();

  // The library's posters and template code are what a user reaches for next,
  // and both load lazily — so open a template that was never loaded online.
  await page.goto('/?template=pop-float&aspect=9:16&frozen=1500');
  await expect(page.locator('canvas')).toBeVisible();
  const painted = await page.evaluate(() => {
    const canvas = document.querySelector('canvas');
    if (!canvas) return 0;
    const ctx = canvas.getContext('2d');
    if (!ctx) return 1; // a WebGL or bitmaprenderer canvas still means it drew
    const { data } = ctx.getImageData(0, 0, canvas.width, canvas.height);
    let lit = 0;
    for (let i = 0; i < data.length; i += 4 * 97) if ((data[i] ?? 0) + (data[i + 1] ?? 0) + (data[i + 2] ?? 0) > 30) lit++;
    return lit;
  });
  expect(painted).toBeGreaterThan(0);

  await context.setOffline(false);
});
