import type { SceneVariant } from '../catalog';

/**
 * Text Motion and Elements (D-119): scenes made of words and simple shapes —
 * what the text-only Corporate Ads are built from, and useful on their own as
 * a title card, a statement, a number, a call to action.
 */

const TEXT_ONLY = { min: 0, max: 0, default: 0 } as const;
const ONE_PHOTO = { min: 1, max: 1, default: 1 } as const;

const type = (
  id: string,
  name: string,
  blurb: string,
  params: SceneVariant['params'],
  durationMs = 4_000,
  photos: SceneVariant['photos'] = TEXT_ONLY,
): SceneVariant => ({ id, name, category: 'Text Motion', family: 'type', blurb, params, photos, durationMs, isNew: true });

const element = (
  id: string,
  name: string,
  blurb: string,
  params: SceneVariant['params'],
  durationMs = 4_500,
): SceneVariant => ({ id, name, category: 'Elements', family: 'element', blurb, params, photos: TEXT_ONLY, durationMs, isNew: true });

const ELEMENTS: readonly SceneVariant[] = [
  element('el-capsule-type', 'Search Capsule', 'A frosted capsule types your question; a button lands inside it.',
    { kind: 'capsule', headline: 'How do I grow my business?', button: 'Ask us' }),
  element('el-cta-button', 'Call to Action', 'A headline, then a button that fills and keeps pulsing.',
    { kind: 'cta', headline: 'Ready when you are', subline: 'Book a free consultation today', button: 'Book now' }),
  element('el-stamp-seal', 'Stamp Seal', 'A round seal stamps down, ringed by turning ticks.',
    { kind: 'stamp', headline: '100% Organic', ring: 'CERTIFIED QUALITY' }),
  element('el-marquee-band', 'Marquee Band', 'A tilted band with your line running endlessly along it.',
    { kind: 'marquee', headline: 'NEW SEASON • NOW IN STORE' }, 5_000),
  element('el-highlight-swipe', 'Highlight Swipe', 'A marker swipes across, and the words appear on it.',
    { kind: 'highlight', headline: 'Free shipping this week', subline: 'On every order, no minimum' }),
  element('el-eq-bars', 'Sound Bars', 'Equaliser bars pulse along the bottom under a bold line.',
    { kind: 'eq', headline: 'The podcast is back', subline: 'New episodes every Monday' }, 5_000),
  element('el-ribbon-banner', 'Ribbon Banner', 'A diagonal ribbon sweeps across carrying the message.',
    { kind: 'ribbon', headline: 'Limited time only', subline: 'Offer ends Sunday' }),
  element('el-orbit-badge', 'Orbit Badge', 'Tilted rings with moons orbiting a centred title.',
    { kind: 'orbit', headline: 'Launching worldwide', subline: 'Available in 40 countries' }, 5_000),
  element('el-pulse-halo', 'Pulse Halo', 'Soft rings ripple outward from the centre like sonar.',
    { kind: 'halo', headline: 'Always listening', subline: 'Support that answers in minutes' }, 5_000),
  element('el-metric-cards', 'Metric Cards', 'Three cards rise in, their numbers counting up.',
    { kind: 'metrics', headline: 'Our year in numbers', stat1: '98%', label1: 'client satisfaction', stat2: '2,400+', label2: 'projects delivered', stat3: '35', label3: 'countries served' }, 5_500),
  element('el-chips', 'Service Chips', 'Your services pop in as chips, then bob gently.',
    { kind: 'chips', headline: 'What we do', chips: 'Branding, Web design, Video, Social media, SEO, Strategy' }, 5_000),
  element('el-eyebrow-title', 'Eyebrow Title', 'A small line, a big title and a rule that draws under it.',
    { kind: 'eyebrow', headline: 'The future of finance', eyebrow: 'INTRODUCING', subline: 'Smart banking for growing businesses' }),
  element('el-claim-pill', 'Claim Pill', 'A bold claim, then a promise stamped on a pill.',
    { kind: 'claim', headline: 'Lower costs. Faster delivery.', promise: 'Guaranteed' }),
  element('el-end-card', 'End Card', 'Your brand, a closing line, a button and your website.',
    { kind: 'end', brand: 'Your Brand', headline: 'Let us build it together', button: 'Get in touch', site: 'yourbrand.com' }),
  element('el-split-reveal', 'Split Reveal', 'Two panels part down the middle to reveal the line.',
    { kind: 'split', headline: 'The wait is over', subline: 'Available from today' }),
  element('el-countdown', 'Countdown', 'Three, two, one — then the announcement.',
    { kind: 'countdown', headline: 'We are live!', subline: 'Join the launch event now' }),
  element('el-checklist', 'Checklist', 'Each point ticks itself off in turn.',
    { kind: 'checklist', headline: 'Why choose us', item1: 'Free consultation', item2: 'Delivery in 48 hours', item3: 'Lifetime support' }, 5_000),
  element('el-review-card', 'Review Card', 'Stars pop in, then a customer review comes into focus.',
    { kind: 'review', headline: 'The best decision we made for our company this year.', name: 'Daniel Mensah, Founder', stars: '★★★★★' }, 5_000),
  element('el-progress-bar', 'Progress Bar', 'A bar fills to your figure as the number counts up.',
    { kind: 'progress', headline: 'Funding goal', value: '87%', subline: 'Thank you to every supporter' }, 5_000),
  element('el-date-card', 'Event Date', 'A calendar card drops in with your date, then the event.',
    { kind: 'date', day: '24', month: 'OCT', headline: 'Annual Leadership Summit', subline: 'Lagos • 9am – 5pm' }),
  element('el-price-tag', 'Price Tag', 'A turning burst, the new price popping in, the old one struck out.',
    { kind: 'price', headline: 'Limited offer', price: '$49', was: '$79' }),
];

export const TEXT_STORY_SCENES: readonly SceneVariant[] = [
  ...ELEMENTS,
  type('type-typewriter', 'Typewriter', 'Letters type on one by one behind a blinking caret.',
    { motion: 'typewriter', unit: 'char', stagger: 55, dur: 1, align: 'left', headline: 'We build tools that save you time.', subline: 'Since 2014' }),
  type('type-mask-wipe', 'Mask Wipe', 'The line is uncovered left to right through a clean mask.',
    { motion: 'mask', accent: 'rule', headline: 'A new way to work', subline: 'Introducing our platform' }),
  type('type-cascade-rise', 'Cascade Rise', 'Words rise into place one after another.',
    { motion: 'rise', unit: 'word', headline: 'Built for teams that move fast', subline: 'Plan, ship and grow together' }),
  // A bold coloured ground, by look rather than by turning the colours inside out (D-121).
  { ...type('type-scale-pop', 'Scale Pop', 'Words pop in with a springy overshoot.',
    { motion: 'pop', unit: 'word', headline: 'Big news is coming', subline: 'Stay tuned' }), look: 'cobalt' },
  type('type-letter-scatter', 'Letter Scatter', 'Letters fly in from scattered places and lock together.',
    { motion: 'scatter', unit: 'char', stagger: 22, dur: 1100, order: 'random', headline: 'Everything comes together', subline: 'One platform, every team' }, 4_500),
  type('type-split-slide', 'Split Slide', 'The two halves of the line slide in from opposite sides.',
    { motion: 'split', unit: 'word', stagger: 0, dur: 900, headline: 'Old way. New way.', subline: 'See the difference' }),
  type('type-soft-focus', 'Soft Focus', 'The line comes out of a soft blur into sharp focus.',
    { motion: 'focus', unit: 'line', dur: 1300, headline: 'Clarity changes everything', subline: 'Our 2026 vision' }, 4_500),
  type('type-underline-draw', 'Underline Draw', 'The line lands, then an accent underline draws beneath it.',
    { motion: 'rise', unit: 'line', accent: 'underline', headline: 'Quality you can measure', subline: 'Certified, tested, trusted' }),
  type('type-stack-drop', 'Stack Drop', 'Big words drop into a tight stack, one on top of another.',
    { motion: 'drop', unit: 'word', layout: 'stack', stagger: 160, dur: 650, sub: false, headline: 'Think bigger move faster' }),
  { ...type('type-punch-swap', 'Punch Swap', 'One phrase punches in, zooms away, and the next punches in.',
    { motion: 'punch', unit: 'word', sub: false, headline: 'Still guessing?', alt: 'Start knowing.' }), look: 'coral' },
  type('type-glitch', 'Glitch Flicker', 'Letters flicker in with split colour channels, then settle.',
    { motion: 'glitch', unit: 'char', stagger: 28, dur: 650, order: 'random', headline: 'Systems online', subline: 'Security that never sleeps' }),
  type('type-wave', 'Wave Letters', 'Letters rise on a wave and keep breathing gently on it.',
    { motion: 'wave', unit: 'char', stagger: 45, dur: 800, headline: 'Good things are flowing', subline: 'Summer collection' }, 4_500),
  type('type-lower-third', 'Lower Third', 'A broadcast bar slides in with a title and a second line.',
    { motion: 'slideRight', unit: 'line', layout: 'third', bg: 'photo', size: 0.058, headline: 'Ada Okafor', subline: 'Chief Executive Officer' }, 4_500, ONE_PHOTO),
  type('type-zoom-title', 'Zoom Title', 'An oversized title zooms down into a settled lockup.',
    { motion: 'zoom', unit: 'line', dur: 1000, headline: 'Grand opening', subline: 'Saturday, 10am' }),
  type('type-rotate-settle', 'Rotate Settle', 'Each word unwinds from a slight tilt as it lands.',
    { motion: 'tilt', unit: 'word', headline: 'Made with care for you', subline: 'Handcrafted in small batches' }),
  type('type-cross-dissolve', 'Cross Dissolve', 'One phrase dissolves into the next in the same place.',
    { motion: 'swap', unit: 'line', sub: false, headline: 'From idea', alt: 'to launch' }),
  type('type-clip-drop', 'Clip Drop', 'Words drop into a crisp window from above.',
    { motion: 'drop', unit: 'word', clip: true, headline: 'Now open in your city', subline: 'Visit us today' }),
  type('type-stagger-fade', 'Stagger Fade', 'A calm word-by-word fade — editorial and quiet.',
    { motion: 'fade', unit: 'word', stagger: 140, dur: 700, align: 'left', layout: 'lower', bg: 'photo', headline: 'Some stories are best told slowly', subline: 'A film by our studio' }, 5_000, ONE_PHOTO),
  type('type-flip', 'Flip In', 'Letters flip open into place along the line.',
    { motion: 'flip', unit: 'char', stagger: 30, dur: 600, headline: 'Flip the script', subline: 'Rethink what is possible' }),
  type('type-tracking-in', 'Tracking In', 'Wide-spaced letters draw together into the word.',
    { motion: 'tracking', unit: 'line', accent: 'rule', headline: 'PREMIUM', subline: 'The new collection' }),
  type('type-big-number', 'Count-Up Number', 'A number counts up to its value, with a line that explains it.',
    { motion: 'count', unit: 'line', size: 0.2, headline: '12,500+', subline: 'businesses trust us every day' }),
  type('type-question-answer', 'Question & Answer', 'A question rises, then its answer pops in underneath.',
    { motion: 'rise', unit: 'word', second: true, sub: false, headline: 'Tired of slow reports?', alt: 'Meet instant insights.' }, 4_500),
  type('type-quote', 'Quote', 'A large quote mark, the words coming into focus, and who said it.',
    { motion: 'focus', unit: 'word', stagger: 90, accent: 'quote', size: 0.07, headline: 'They changed how our whole team works.', subline: '— Maria Chen, Operations Lead' }, 5_000),
];
